### ISSUE TITLE
git stash viewing busted - visual studio code on ubuntu 16.04

### ISSUE THREAD

**Issue by adowdy** [matsken/git-stash-viewer#1]
Can't seem to view my Q&A on VSC page anymore about this.

Gist is, I can see the GIT STASH item in Explorer view, but when I click it I can't interact or see the contents of the stash. Running Ubuntu 16.04 x64, just installed Visual Studio Code today and I like it, tinkering around with mods such as yours! Thanks!

git stash list
(output below)
stash@{0}: WIP on (no branch): 55c8a76 pcsc-lite: Seperate GPLV3 portions from BSD

git stash show
(output below... i edited one line in one file and stashed it)
 meta-multimedia/recipes-multimedia/vlc/vlc.inc | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

**Comment by matsken** [comment]
@nerael Thanks for reporting - Looks like when I added the git repo integration with VS marketplace, it removed the Q&A feature. Sorry about that.
I've since updated the version, so can you try the latest?

**Comment by adowdy** [comment]
v 0.1.9 ... is that it? Still see the same issue I believe. See screenshot. When clicked on, error is at top!

![vsc-gitstash-1](https://user-images.githubusercontent.com/8887512/30459029-07de2956-9963-11e7-9bb9-5124bd5d8e1d.png)

**Comment by matsken** [comment]
@nerael What do you get when you run `git stash show 0` manually?  I'm also adding some more error handling with 0.1.10.

**Comment by adowdy** [comment]
if i type `git stash show 0`

fatal: ambiguous argument '0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'`

if i type `git stash show -p stash@{0}`

diff --git a/meta-multimedia/recipes-multimedia/vlc/vlc.inc b/meta-multimedia/recipes-multimedia/vlc/vlc.inc
index 8142e16..389473d 100644
--- a/meta-multimedia/recipes-multimedia/vlc/vlc.inc
+++ b/meta-multimedia/recipes-multimedia/vlc/vlc.inc
@@ -49,7 +49,7 @@ PACKAGECONFIG[postproc] = "--enable-postproc,--disable-postproc,libpostproc"
 PACKAGECONFIG[opencv] = "--enable-opencv,--disable-opencv,opencv"
 PACKAGECONFIG[libva] = "--enable-libva --enable-avcodec,--disable-libva --disable-avcodec,libva libav"
 PACKAGECONFIG[speex] = "--enable-speex,--disable-speex,speex"
-PACKAGECONFIG[gstreamer] = "--enable-gst-decode,--disable-gst-decode,gstreamer1.0 gstreamer1.0-plugins-base gst-plugins-bad"
+PACKAGECONFIG[gstreamer] = "--enable-gst-decode,--disable-gst-decode,gstreamer1.0 gstreamer1.0-plugins-base gst-plugins-bad gst-plugins-ugly"
 PACKAGECONFIG[vpx] = "--enable-vpx,--disable-vpx, libvpx"
 PACKAGECONFIG[qt4] = "--enable-qt,--disable-qt, qt4-x11-free"
 PACKAGECONFIG[freerdp] = "--enable-freerdp,--disable-freerdp, freerdp"


------

It doesn't recognize 0, but it recognizes this other formatting - that is indeed the diff from my stash in output! I pulled it out of the description under `git stash show --help`

**Comment by matsken** [comment]
I think I know the cause -- do you have the Git `stash.showPatch` option set to true?  I think with this option, the stash name needs to be more explicit.  I've made a fix in `v0.1.11`.

**Comment by adowdy** [comment]
I don't have `stash.showPatch` active to my knowledge, unless it's default. I updated, the error went away. Seems better! I can at least see the stash output in the 'Explorer' frame now.

From here, are you hoping to add the ability to pop stash contents? That would rock! Thanks

**Comment by matsken** [comment]
@nerael Yes, that is the plan!
